version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blog-app
    ports:
      - "80:80"
    networks:
      - default
    restart: always
    environment:
      PORT: $PORT
    mem_limit: 512m

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_PORT: $MYSQL_PORT
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    ports:
      - '3306:3306'
    volumes:
      - ./mysql-data:/var/lib/mysql

  restore: # Restore MySql Pscale Dump
    image: alpine:latest
    volumes:
      - ./restore.sh:/docker-entrypoint-initdb.d/restore.sh
    environment:
      MYSQL_HOST: db
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      RESTORE_URL: $RESTORE_URL
    command: ["/bin/sh", "-c", "apk add --no-cache mysql-client mariadb-connector-c curl unzip bash && chmod +x /docker-entrypoint-initdb.d/restore.sh && /docker-entrypoint-initdb.d/restore.sh"]
    depends_on:
      - db
