version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blog-app
    ports:
      - "80:80"
    networks:
      - default
    restart: always
    environment:
      PORT: $PORT
      MYSQL_HOST: database
      MYSQL_PORT: $MYSQL_PORT
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    depends_on:
      - database
    mem_limit: 512m

networks:
  default:
    external: true

