version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blog-app
    ports:
      - "8080:8080"
    networks:
      - local_net
    environment:
      PORT: $PORT
      MYSQL_HOST: $MYSQL_HOST
      MYSQL_PORT: $MYSQL_PORT
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    depends_on:
      - database
    mem_limit: 512m
    cpus: "1.0"
  database:
    image: mysql:5.7
    container_name: blog-db
    networks:
      - local_net
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql 
      - ./blog.sql:/docker-entrypoint-initdb.d/blog.sql 
    mem_limit: 512m 
    cpus: "1.0"
    env_file:
      - .env
volumes:
  mysql_data:
