version: '3.8'
services:
  database:
    image: mysql:5.7
    container_name: blog-db
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3037:3306"
    networks:
      - default
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql 
      - ./blog.sql:/docker-entrypoint-initdb.d/blog.sql 

volumes:
  mysql_data:
