name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Build the Docker image
      run: |
        docker login --username kevingil --password ${{ secrets.GH_PAT }} ghcr.io
        docker build -t ghcr.io/kevingil/blog:latest -f app/Dockerfile .
        docker push ghcr.io/kevingil/blog:latest
